### ISSUE TITLE
TORGMHとSSPの競合について

### ISSUE THREAD

**Issue by Shanpan2** [satsumaimoamo/SuperSimplePlus#3]
初Issue失礼します。いつもTORGMHなどのMODを使う際にSSPを使わせていただいており、感謝しています。
今回のAmong UsのV2022.10.25のアップデートにおきまして、TORGM-Hmodのv2022.10.20(公式アプデ仮対応でテスト版)とSSPmodのv1.40でTORGM-Hの文字が表示されないというバグが発生しているためできれば出来れば修正のほうをお願いします。
[
![20221022105040_1](https://user-images.githubusercontent.com/113867056/197314616-f7676c39-d203-47a8-ba98-af97d7cb4a4c.jpg)
](url)

**Comment by Kurato-Tsukishiro** [comment]
こっちじゃないこっちじゃない

開発者同じやって
こっちは()

**Comment by Shanpan2** [comment]
あー了解です
